files:
  evidence: data/phsites-evidence.txt
  keys: data/keys.txt
  contrasts: data/contrast.txt
  summary: data/summary.txt
  output: quant-phsites/phsites-results.txt
qc:
  basic: 0
  extended: 0
  extendedSummary: 0
data:
  enabled: 1
  fractions:
    enabled: 0
  silac:
    enabled: 0
  filters:
    enabled: 1
    contaminants: 1
    protein_groups: remove
    modifications: PH
  sample_plots: 1
msstats:
  enabled: 1
  msstats_input:
  profilePlots: none
  normalization_method: equalizeMedians
  normalization_reference:
  summaryMethod: TMP
  censoredInt: NA
  cutoffCensored: minFeature
  MBimpute: 1
  feature_subset: all
output_extras:
  enabled: 1
  annotate:
    enabled: 1
    species: HUMAN
  plots:
    volcano: 1
    heatmap: 1
    LFC: -0.58 0.58
    FDR: 0.05
    heatmap_cluster_cols: 0
    heatmap_display: log2FC